name: local_auth_passcode
description: A Local Auth 
version: 0.1.2
homepage: 

environment:
  sdk: '>=3.1.0 <4.0.0'  

dependencies:
  flutter:
    sdk: flutter
  # keyboard_visibility: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
