name: local_auth_passcode
description: A Local Auth 
version: 0.1.1
author: Tierra Tech Developers <devteam@tierratech.net>
homepage: 

environment:
  sdk: '2.10.5'
  flutter: "1.22.6"

dependencies:
  flutter:
    sdk: flutter
  # keyboard_visibility: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
